name: Node.js CI

#

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js 18.x
      uses: actions/setup-node@v4
      with:
        node-version: '18.x'
        cache: 'npm'

    - run: npm ci
    - run: npm run build --if-present
    - run: npm run export --if-present

    - name: Set up Git configuration
      run: |
        git config user.name "amanmehtacode"
        git config user.email "amehta20@nyit.edu"

    - name: Deploy to GitHub Pages
      if: github.ref == 'refs/heads/main'
      run: npm run deploy
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
